<a href="https://colab.research.google.com/github/dozhash/ai_foundation/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# pip install numpy

In [3]:
import numpy as np

In [11]:
arr = np.array([1,2,3,4,5])
print("numpy_array:", arr)

arr.shape

numpy_array: [1 2 3 4 5]


(5,)

In [12]:
arr2 = np.array([[1,2,3,4], [5, 6, 7, 8]])
print("numpy_array:", arr)

arr2.shape

numpy_array: [1 2 3 4 5]


(2, 4)

In [14]:
# dtype()
a = np.array([1, 2, 3])
print(a.dtype)

int64


In [16]:
# reshape()
a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape(2, 3)
print("shaped_array:", b)

shaped_array: [[1 2 3]
 [4 5 6]]


In [17]:
# astype()
a = np.array([1, 2, 3])
b = a.astype(float)
print("float:", b)

float: [1. 2. 3.]


In [19]:
# np.zeros(), np.ones()
z = np.zeros((2, 3))
o = np.ones((2, 3))

print("zeros:", z)
print("ones:", o)

zeros: [[0. 0. 0.]
 [0. 0. 0.]]
ones: [[1. 1. 1.]
 [1. 1. 1.]]


In [20]:
# ndim
a = np.array([[1, 2], [3, 4]])
print("ndim:", a.ndim)

ndim: 2


In [21]:
# arange()
a = np.arange(1, 6)
print("aramge:", a)

aramge: [1 2 3 4 5]


In [22]:
# sum(), mean(), max(), min()

a = np.array([1, 2, 3, 4])

print("sum:", a.sum())
print("mean:", a.mean())
print("max:", a.max())
print("min:", a.min())

sum: 10
mean: 2.5
max: 4
min: 1


In [23]:
# flatten()
a = np.array([[1, 2], [3, 4]])
print('flatten:', a.flatten())

flatten: [1 2 3 4]


In [24]:
# T (Transpose)
a = np.array([[1, 2], [3, 4]])
print("transpose:", a.T)

transpose: [[1 3]
 [2 4]]


In [25]:
# dot() @
a = np.array([[1, 2], [3, 4]])
b = np.array([[2, 0], [1, 2]])
print("dot/multiplication:", a.dot(b))

dot/multiplication: [[ 4  4]
 [10  8]]


In [27]:
# random.rand()
a = np.random.rand(2, 3) # => 0.0 and 1.0 | 0.0 -> included / 1.0 -> excluded
print("random rand:", a)

random rand: [[0.14053763 0.21899818 0.40669194]
 [0.88069048 0.68987225 0.79461541]]
